### ISSUE TITLE
make generate error

### ISSUE THREAD

**Issue by pss-coder** [Jake-Prickett/SpeechToText-gRPC-iOS#3]
Hi, following your readme, when I enter `make generate`, I get the following error:

<img width="512" alt="Screenshot 2022-08-10 at 11 16 22 PM" src="https://user-images.githubusercontent.com/22881285/184021739-a171aba3-255c-4f41-87c5-600477f5e745.png">

Am I missing a certain dependency to be installed?

**Comment by Jake-Prickett** [comment]
Great catch - it seems you are missing the `protoc` plugins required to generate the client code. I mention it in the article but not in the Project Setup. (I'll add it in 👍)

It can be installed via homebrew using the following command: `brew install swift-protobuf grpc-swift`.

**Comment by pss-coder** [comment]
Great, it works now! Thank you.
